apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: expose
  name: expose
  namespace: expose
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expose
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: expose
    spec:
      containers:
      - image: viveksinghggits/expose:0.1.0
        name: expose
        resources: {}
      serviceAccountName: expose-sa
status: {}
